# constants file for BBDN-REST_DEMO-Python

#IDs for create
DSKEXTERNALID = 'BBDN-PYTHON-REST-DEMO-DSK'
COURSEEXTERNALID = 'BBDN-PYTHON-REST-DEMO-COURSE'
TERMEXTERNALID = 'BBDN-PYTHON-REST-DEMO-TERM'
USEREXTERNALID = 'BBDN-PYTHON-REST-DEMO-USER'
PAGINATIONLIMIT = 5
COURSEGETFIELDS = 'externalId,courseId,name,availability,id'
USERGETFIELDS = 'externalId,name'
TERMSGETFIELDS = 'externalId,name'
DSKSGETFIELDS = 'externalId,name'
CRSMEMBERSHIPGETFIELDS = "externalId,availability"
USRMEMBERSHIPGETFIELDS = "externalId,availability"
CERTPATH = "./trusted/keytool_crt.pem"

